Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

packagename = 'testfwFoundation'
libEnv.Tool(packagename + 'Lib', depsOnly=1)
#progEnv.Tool('registerObjects', package=packagename)

#print libEnv.Dump()
#print progEnv.Dump()
