import StanfordUtils

progEnv = StanfordUtils.CloneBaseEnv()

packagename = 'testfwFoundation'

StanfordUtils.DependsOn(progEnv, packagename, depsOnly=1)
#progEnv.Tool('registerObjects', package=packagename)

