import SConsider, pdb

progEnv = SConsider.CloneBaseEnv()

targetname='LDAPDAICacheHandler_Test'
SConsider.DependsOn(progEnv, 'CoastLDAPDAICacheHandler')
SConsider.DependsOn(progEnv, 'testfwWDBase')
createdProgram = progEnv.Program(targetname, SConsider.listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=targetname, testApps=[createdProgram], config=SConsider.listFiles(['config/*.any', 'config/*.txt', 'config/*.tst', 'config/testscript.sh', 'config/prjconfig.sh', 'tmp/*.any']))

