import pdb
Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()

progEnv.Tool('mtfoundationLib')
progEnv.Tool('testfwFoundationLib')
mtfoundation_Test = progEnv.Program('mtfoundation_Test', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='mtfoundation_Test', testApps=[mtfoundation_Test])

#print progEnv.Dump()
