import StanfordUtils

targetname = 'mtfoundation_Test'

progEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(progEnv, 'CoastMTFoundation')
StanfordUtils.DependsOn(progEnv, 'testfwFoundation')
createdProgram = progEnv.Program(targetname, StanfordUtils.listFilestils.listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=targetname, testApps=[createdProgram], config=StanfordUtils.listFilesnfig=StanfordUtils.listFiles(['config/*.any', 'config/prjconfig.sh']))

