Import('baseEnv')
Import('listFiles')

progEnv=baseEnv.Clone()
libEnv=baseEnv.Clone()
libEnv.Tool('coast_options')

libEnv.Tool('mtfoundationLib', depsOnly = 1)
mtfoundationLib=libEnv.SharedLibrary('mtfoundation', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='coast_mtfoundation', libraries=[mtfoundationLib], includes=listFiles(['*.h','*.ipp']))

#print libEnv.Dump()
#print progEnv.Dump()
