Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

packagename = 'mtfoundation'
libEnv.Tool(packagename + 'Lib', depsOnly=1)
mtfoundationLib = libEnv.SharedLibrary('mtfoundation', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=packagename, libraries=[mtfoundationLib])

#print libEnv.Dump()
#print progEnv.Dump()
