  DROP TABLE "BONUS" cascade constraints;
  DROP TABLE "DEPT" cascade constraints;
  DROP TABLE "EMP" cascade constraints;
  DROP TABLE "SALGRADE" cascade constraints;
  DROP FUNCTION "GETMAXSALARY";
  DROP PROCEDURE "GETEMPNAME";
  DROP PROCEDURE "GETEMPS";
  DROP PROCEDURE "GETEMPSALARY";
  DROP PROCEDURE "GETFIRSTEMPNAME";
  DROP PROCEDURE "GETFLOAT";
  DROP PROCEDURE "GETMAXSALARYPROC";
  DROP PROCEDURE "GETSTRING";
  