Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

packagename = 'CoastAccessControl'
libEnv.Tool(packagename + 'Lib', depsOnly=1)
createdLib = libEnv.SharedLibrary(packagename, listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=packagename, libraries=[createdLib])

#print libEnv.Dump()
#print progEnv.Dump()
