Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()

targetname = 'wdapp'
progEnv.Tool('CoastWDBaseLib')
wdapp = progEnv.Program(targetname, listFiles(['Main.cpp']))
Export('wdapp')

#print progEnv.Dump()
