import StanfordUtils

targetname = 'wdapp'

progEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(progEnv, targetname, depsOnly=1)

wdapp = progEnv.Program(targetname, StanfordUtils.listFiles(['Main.cpp']))
Export(targetname)
progEnv.Alias(targetname, wdapp)
