import StanfordUtils

targetname = 'wdapp'

progEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(progEnv, targetname, depsOnly=1)

progEnv.Program(targetname, StanfordUtils.listFiles(['Main.cpp']))
