import StanfordUtils

Import('baseEnv')
Import('listFiles')

progEnv=baseEnv.Clone()
progEnv.AppendUnique(CPPDEFINES =['ONLY_STD_IOSTREAM'])
progEnv.AppendUnique(CPPDEFINES =['_POSIX_THREADS'])
progEnv.AppendUnique(CPPDEFINES =['_POSIX_PTHREAD_SEMANTICS'])
progEnv.AppendUnique(CPPDEFINES =['_REENTRANT'])
progEnv.AppendUnique(CPPDEFINES =['_LARGEFILE64_SOURCE'])
progEnv.AppendUnique(CPPDEFINES =['WD_OPT'])

progEnv.Tool('foundationLib')
progEnv.Tool('testfwLib')
foundation_Test=progEnv.Program('wdtest',listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='coast_foundation_Test', libraries=[], includes=[], binaries=[foundation_Test])

#print progEnv.Dump()
#print progEnv.Dump()
