Import('baseEnv')
Import('listFiles')

progEnv=baseEnv.Clone()
libEnv=baseEnv.Clone()
libEnv.Tool('coast_options')

libEnv.Tool('testfwLib', depsOnly = 1)
testfwLib=libEnv.StaticLibrary('testfw', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='coast_testfw', libraries=[testfwLib], includes=listFiles(['*.h']))

#print libEnv.Dump()
#print progEnv.Dump()
