Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

packagename = 'testfw'
libEnv.Tool(packagename + 'Lib', depsOnly=1)
libEnv['_NONLAZYLINKFLAGS'] = ''
createdLib = libEnv.SharedLibrary('testfw', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=packagename, libraries=[createdLib])

#print libEnv.Dump()
#print progEnv.Dump()
