import platform
import StanfordUtils

Import('baseEnv')
Import('listFiles')

progEnv=baseEnv.Clone()
libEnv=baseEnv.Clone()
libEnv.AppendUnique(CPPDEFINES =['ONLY_STD_IOSTREAM'])

testfwLib=libEnv.StaticLibrary('testfw', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='coast_testfw', libraries=[testfwLib], includes=listFiles(['*.h']))

print libEnv.Dump()
#print progEnv.Dump()
