import StanfordUtils, pdb

progEnv = StanfordUtils.CloneBaseEnv()

targetname='MySQL_Test'
StanfordUtils.DependsOn(progEnv, 'CoastMySQL')
StanfordUtils.DependsOn(progEnv, 'testfwWDBase')
createdProgram = progEnv.Program(targetname, StanfordUtils.listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=targetname, testApps=[createdProgram], config=StanfordUtils.listFiles(['config/*.any', 'config/*.txt', 'config/*.tst', 'config/testscript.sh', 'config/prjconfig.sh', 'tmp/*.any']))

