import StanfordUtils

progEnv = StanfordUtils.CloneBaseEnv()
libEnv = StanfordUtils.CloneBaseEnv()

packagename = 'CoastPerfTest'
StanfordUtils.DependsOn(libEnv, packagename, depsOnly=1)
createdLib = libEnv.SharedLibrary(packagename, StanfordUtils.listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=packagename, libraries=[createdLib])

