import StanfordUtils, pdb

packagename = 'PerfTestTest'

libEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(libEnv, packagename, depsOnly=1)
createdLib = libEnv.SharedLibrary(packagename, StanfordUtils.listFiles(['*.cpp']))

progEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(progEnv, 'wdapp')
Import('wdapp')

progEnv.Tool('registerObjects', package=packagename,
             libraries=[createdLib],
             requiresLibs=['CoastStdDataAccess', 'CoastActions', 'CoastRenderers'],
             testApps=[wdapp],
             config=StanfordUtils.listFiles(['*.txt', '*.html', '*.any']))
