import StanfordUtils

packagename = 'CoastFoundation'

libEnv = StanfordUtils.CloneBaseEnv()
StanfordUtils.DependsOn(libEnv, packagename, depsOnly=1)
createdLib = libEnv.SharedLibrary(packagename, StanfordUtils.listFiles(['*.cpp']))

progEnv = StanfordUtils.CloneBaseEnv()
progEnv.Tool('registerObjects', package=packagename, libraries=[createdLib])
