Import('baseEnv')
import SomeUtils
from SomeUtils import *

progEnv = baseEnv.Clone()
libEnv = baseEnv.Clone()

packagename = 'foundation'
libEnv.Tool(packagename + 'Lib', depsOnly=1)
foundationLib = libEnv.SharedLibrary('foundation', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package=packagename, libraries=[foundationLib])

#print libEnv.Dump()
#print progEnv.Dump()
