Import('baseEnv')
Import('listFiles')

progEnv=baseEnv.Clone()
libEnv=baseEnv.Clone()

libEnv.Tool('foundationLib', depsOnly = 1)
foundationLib=libEnv.SharedLibrary('foundation', listFiles(['*.cpp']))
progEnv.Tool('registerObjects', package='coast_foundation', libraries=[foundationLib], includes=listFiles(['*.h']))

#print libEnv.Dump()
#print progEnv.Dump()
